"use client"

import { deleteGroup, deleteShortcut, listShortcutGroups, listShortcuts, moveShortcut, saveGroup, saveShortcut, type Shortcut, type ShortcutGroup } from '@/app/actions/shortcuts'
import { Button } from '@/components/ui/button'
import { Field, TextInput } from '@/components/form-controls'
import { Edit3, ExternalLink, Folder, FolderOpen, ImagePlus, Plus, Trash2, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'

const EMPTY_FORM = { name: '', link: '', imageUrl: '', groupId: '' }

export function ShortcutManager() {
  const [items, setItems] = useState<Shortcut[]>([])
  const [groups, setGroups] = useState<ShortcutGroup[]>([])
  const [activeGroup, setActiveGroup] = useState<string | null>(null)
  const [open, setOpen] = useState<'shortcut' | 'group' | null>(null)
  const [editing, setEditing] = useState<Shortcut | null>(null)
  const [editingGroup, setEditingGroup] = useState<ShortcutGroup | null>(null)
  const [form, setForm] = useState(EMPTY_FORM)
  const [groupName, setGroupName] = useState('')
  const [selectedFile, setSelectedFile] = useState<File | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const fileInputRef = useRef<HTMLInputElement>(null)

  async function refresh() { setLoading(true); const [nextGroups, nextItems] = await Promise.all([listShortcutGroups(), listShortcuts()]); setGroups(nextGroups); setItems(nextItems); setLoading(false) }
  useEffect(() => { refresh().catch(() => setLoading(false)) }, [])

  function startShortcut(item?: Shortcut) { setEditing(item ?? null); setSelectedFile(null); setError(''); setForm(item ? { name: item.name, link: item.link, imageUrl: item.imageUrl, groupId: item.groupId ?? '' } : { ...EMPTY_FORM, groupId: activeGroup ?? '' }); setOpen('shortcut') }
  function startGroup(group?: ShortcutGroup) { setEditingGroup(group ?? null); setGroupName(group?.name ?? ''); setError(''); setOpen('group') }
  function selectFile(file?: File) { if (!file) return; if (!file.type.startsWith('image/') || file.size > 5 * 1024 * 1024) { setError('Escolha uma imagem de até 5 MB.'); return }; setSelectedFile(file); setForm((current) => ({ ...current, imageUrl: URL.createObjectURL(file) })) }
  async function submitGroup(event: React.FormEvent) { event.preventDefault(); if (!groupName.trim()) return; setSaving(true); try { await saveGroup({ id: editingGroup?.id, name: groupName.trim() }); setOpen(null); await refresh() } finally { setSaving(false) } }
  async function submitShortcut(event: React.FormEvent) {
    event.preventDefault(); if (!form.name.trim() || !form.link.trim() || (!form.imageUrl && !selectedFile)) return
    setSaving(true); setError('')
    try { let imageUrl = form.imageUrl; if (selectedFile) { const body = new FormData(); body.append('file', selectedFile); const response = await fetch('/api/shortcuts/upload', { method: 'POST', body }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'Não foi possível enviar a imagem.'); imageUrl = result.url }; await saveShortcut({ id: editing?.id, name: form.name.trim(), link: form.link.trim(), imageUrl, groupId: form.groupId || null }); setOpen(null); await refresh() } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível salvar o atalho.') } finally { setSaving(false) }
  }
  async function removeGroup(group: ShortcutGroup) { if (window.confirm(`Excluir a pasta “${group.name}”? Os atalhos ficarão em Sem grupo.`)) { await deleteGroup(group.id); if (activeGroup === group.id) setActiveGroup(null); await refresh() } }
  async function removeShortcut(id: string) { if (window.confirm('Excluir este atalho?')) { await deleteShortcut(id); await refresh() } }

  const visible = activeGroup === null ? items.filter((item) => !item.groupId) : items.filter((item) => item.groupId === activeGroup)
  const currentName = activeGroup ? groups.find((group) => group.id === activeGroup)?.name : 'Sem grupo'

  return <div className="flex flex-col gap-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-base font-semibold">Meus atalhos</h2><p className="text-sm text-muted-foreground">Organize seus links em pastas.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => startGroup()}><Folder /> Nova pasta</Button><Button onClick={() => startShortcut()}><Plus /> Novo atalho</Button></div></div>
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{groups.map((group) => { const groupItems = items.filter((item) => item.groupId === group.id); return <article key={group.id} className={`group relative cursor-pointer rounded-2xl border bg-card p-4 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md ${activeGroup === group.id ? 'border-primary ring-1 ring-primary/30' : 'border-border'}`} onClick={() => setActiveGroup(group.id)}><div className="flex items-start justify-between"><FolderOpen className="size-8 text-primary" /><div className="flex gap-1 opacity-0 transition group-hover:opacity-100"><button type="button" onClick={(event) => { event.stopPropagation(); startGroup(group) }} aria-label="Renomear pasta" className="rounded-md p-1.5 text-muted-foreground hover:bg-muted"><Edit3 className="size-3.5" /></button><button type="button" onClick={(event) => { event.stopPropagation(); removeGroup(group) }} aria-label="Excluir pasta" className="rounded-md p-1.5 text-muted-foreground hover:bg-destructive/10 hover:text-destructive"><Trash2 className="size-3.5" /></button></div></div><p className="mt-4 font-semibold">{group.name}</p><div className="mt-3 flex -space-x-2">{groupItems.slice(0, 4).map((item) => <img key={item.id} src={item.imageUrl} alt="" className="size-8 rounded-lg border-2 border-card object-cover" />)}{groupItems.length === 0 ? <span className="text-xs text-muted-foreground">Pasta vazia</span> : null}</div><p className="mt-3 text-xs text-muted-foreground">{groupItems.length} {groupItems.length === 1 ? 'atalho' : 'atalhos'}</p></article>})}<article className={`cursor-pointer rounded-2xl border border-dashed bg-card p-4 transition hover:bg-muted/40 ${activeGroup === null ? 'border-primary' : 'border-border'}`} onClick={() => setActiveGroup(null)}><div className="flex items-start justify-between"><Folder className="size-8 text-muted-foreground" /><span className="rounded-full bg-muted px-2 py-1 text-[10px] font-medium">Padrão</span></div><p className="mt-4 font-semibold">Sem grupo</p><p className="mt-3 text-xs text-muted-foreground">{items.filter((item) => !item.groupId).length} atalhos</p></article></div>
    <div className="flex items-center justify-between border-b border-border pb-3"><div><h3 className="font-semibold">{currentName}</h3><p className="text-xs text-muted-foreground">{visible.length} {visible.length === 1 ? 'atalho' : 'atalhos'}</p></div>{activeGroup ? <Button variant="ghost" size="sm" onClick={() => setActiveGroup(null)}>Ver sem grupo</Button> : null}</div>
    {loading ? <div className="rounded-2xl border border-border bg-card p-8 text-center text-sm text-muted-foreground">Carregando atalhos...</div> : visible.length === 0 ? <div className="rounded-2xl border border-dashed border-border bg-card p-10 text-center"><ImagePlus className="mx-auto mb-3 size-8 text-muted-foreground" /><p className="text-sm text-muted-foreground">Nenhum atalho neste grupo.</p></div> : <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{visible.map((item) => <article key={item.id} className="overflow-hidden rounded-2xl border border-border bg-card shadow-sm"><a href={item.link} target="_blank" rel="noreferrer" className="block"><img src={item.imageUrl} alt={item.name} className="h-40 w-full object-cover" /><div className="flex items-center justify-between gap-3 p-4"><div className="min-w-0"><h3 className="truncate font-semibold">{item.name}</h3><p className="truncate text-xs text-muted-foreground">{item.link}</p></div><ExternalLink className="size-4 shrink-0 text-muted-foreground" /></div></a><div className="flex gap-2 border-t border-border p-3"><Button variant="outline" size="sm" className="flex-1" onClick={() => startShortcut(item)}><Edit3 /> Editar</Button><Button variant="ghost" size="icon-sm" onClick={() => removeShortcut(item.id)} aria-label="Excluir atalho"><Trash2 /></Button></div></article>)}</div>}
    {open === 'group' ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/40 p-4"><form onSubmit={submitGroup} className="w-full max-w-md rounded-2xl border border-border bg-card shadow-xl"><div className="flex items-center justify-between border-b border-border px-5 py-4"><h2 className="font-semibold">{editingGroup ? 'Renomear pasta' : 'Nova pasta'}</h2><button type="button" onClick={() => setOpen(null)} aria-label="Fechar"><X /></button></div><div className="px-5 py-5"><Field label="Nome da pasta" htmlFor="group-name"><TextInput id="group-name" value={groupName} onChange={setGroupName} placeholder="Ex.: Modelagem 3D" /></Field></div><div className="flex gap-2 border-t border-border px-5 py-4"><Button type="button" variant="outline" className="flex-1" onClick={() => setOpen(null)}>Cancelar</Button><Button type="submit" className="flex-1" disabled={saving}>Salvar</Button></div></form></div> : null}
    {open === 'shortcut' ? <div className="fixed inset-0 z-50 flex items-center justify-center bg-foreground/40 p-4"><form onSubmit={submitShortcut} className="w-full max-w-md rounded-2xl border border-border bg-card shadow-xl"><div className="flex items-center justify-between border-b border-border px-5 py-4"><h2 className="font-semibold">{editing ? 'Editar atalho' : 'Novo atalho'}</h2><button type="button" onClick={() => setOpen(null)} aria-label="Fechar"><X /></button></div><div className="flex flex-col gap-4 px-5 py-5"><Field label="Nome" htmlFor="shortcut-name"><TextInput id="shortcut-name" value={form.name} onChange={(value) => setForm((current) => ({ ...current, name: value }))} placeholder="Ex.: Thingiverse" /></Field><Field label="Link" htmlFor="shortcut-link"><TextInput id="shortcut-link" value={form.link} onChange={(value) => setForm((current) => ({ ...current, link: value }))} placeholder="https://..." /></Field><Field label="Grupo" htmlFor="shortcut-group"><select id="shortcut-group" value={form.groupId} onChange={(event) => setForm((current) => ({ ...current, groupId: event.target.value }))} className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm"><option value="">Sem grupo</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></Field><Field label="Imagem" htmlFor="shortcut-image"><input ref={fileInputRef} id="shortcut-image" type="file" accept="image/*" className="sr-only" onChange={(event) => selectFile(event.target.files?.[0])} /><button type="button" onClick={() => fileInputRef.current?.click()} className="flex w-full items-center gap-3 rounded-xl border border-dashed border-border bg-muted/30 p-3 text-left hover:bg-muted"><ImagePlus className="size-5 text-muted-foreground" /><span className="truncate text-sm text-muted-foreground">{selectedFile?.name || (editing ? 'Escolher nova imagem (opcional)' : 'Escolher imagem')}</span></button>{form.imageUrl ? <img src={form.imageUrl} alt="Pré-visualização" className="mt-2 h-24 w-full rounded-xl object-cover" /> : null}<p className="text-xs text-muted-foreground">PNG, JPG ou WEBP, até 5 MB.</p></Field>{error ? <p role="alert" className="text-sm text-destructive">{error}</p> : null}</div><div className="flex gap-2 border-t border-border px-5 py-4"><Button type="button" variant="outline" className="flex-1" onClick={() => setOpen(null)}>Cancelar</Button><Button type="submit" className="flex-1" disabled={saving}>{saving ? 'Salvando...' : 'Salvar'}</Button></div></form></div> : null}
  </div>
}
